---
title: "Classifying Luca Data"
author: "Daniel"
date: "2024-11-07"
output: html_document
---
```{r}
library(tidyverse)
```


```{r}
#| label: read-data

ERR1307111 <- read.csv("C:/Users/danie/OneDrive/Documents/Wray_Lab/gynandromorph_2024/ERR1307111.bedgraph.csv")
ERR1307112 <- read.csv("C:/Users/danie/OneDrive/Documents/Wray_Lab/gynandromorph_2024/ERR1307112.bedgraph.csv")
ERR1307113 <- read.csv("C:/Users/danie/OneDrive/Documents/Wray_Lab/gynandromorph_2024/ERR1307113.bedgraph.csv")
ERR2298201 <- read.csv("C:/Users/danie/OneDrive/Documents/Wray_Lab/gynandromorph_2024/ERR2298201.bedgraph.csv")
ERR2298204 <- read.csv("C:/Users/danie/OneDrive/Documents/Wray_Lab/gynandromorph_2024/ERR2298204.bedgraph.csv")
ERR2298205 <- read.csv("C:/Users/danie/OneDrive/Documents/Wray_Lab/gynandromorph_2024/ERR2298205.bedgraph.csv")
ERR2298206 <- read.csv("C:/Users/danie/OneDrive/Documents/Wray_Lab/gynandromorph_2024/ERR2298206.bedgraph.csv")
ERR2298207 <- read.csv("C:/Users/danie/OneDrive/Documents/Wray_Lab/gynandromorph_2024/ERR2298207.bedgraph.csv")
ERR2298208 <- read.csv("C:/Users/danie/OneDrive/Documents/Wray_Lab/gynandromorph_2024/ERR2298208.bedgraph.csv")
ERR2298209 <- read.csv("C:/Users/danie/OneDrive/Documents/Wray_Lab/gynandromorph_2024/ERR2298209.bedgraph.csv")
ERR2298210 <- read.csv("C:/Users/danie/OneDrive/Documents/Wray_Lab/gynandromorph_2024/ERR2298210.bedgraph.csv")
ERR2298211 <- read.csv("C:/Users/danie/OneDrive/Documents/Wray_Lab/gynandromorph_2024/ERR2298211.bedgraph.csv")
ERR2298214 <- read.csv("C:/Users/danie/OneDrive/Documents/Wray_Lab/gynandromorph_2024/ERR2298214.bedgraph.csv")
ERR2298216 <- read.csv("C:/Users/danie/OneDrive/Documents/Wray_Lab/gynandromorph_2024/ERR2298216.bedgraph.csv")
ERR2298219 <- read.csv("C:/Users/danie/OneDrive/Documents/Wray_Lab/gynandromorph_2024/ERR2298219.bedgraph.csv")
ERR2298221 <- read.csv("C:/Users/danie/OneDrive/Documents/Wray_Lab/gynandromorph_2024/ERR2298221.bedgraph.csv")
ERR2298224 <- read.csv("C:/Users/danie/OneDrive/Documents/Wray_Lab/gynandromorph_2024/ERR2298224.bedgraph.csv")
ERR2298230 <- read.csv("C:/Users/danie/OneDrive/Documents/Wray_Lab/gynandromorph_2024/ERR2298230.bedgraph.csv")
ERR2298231 <- read.csv("C:/Users/danie/OneDrive/Documents/Wray_Lab/gynandromorph_2024/ERR2298231.bedgraph.csv")
ERR2298233 <- read.csv("C:/Users/danie/OneDrive/Documents/Wray_Lab/gynandromorph_2024/ERR2298233.bedgraph.csv")
ERR2298234 <- read.csv("C:/Users/danie/OneDrive/Documents/Wray_Lab/gynandromorph_2024/ERR2298234.bedgraph.csv")
ERR2298235 <- read.csv("C:/Users/danie/OneDrive/Documents/Wray_Lab/gynandromorph_2024/ERR2298235.bedgraph.csv")
ERR2298236 <- read.csv("C:/Users/danie/OneDrive/Documents/Wray_Lab/gynandromorph_2024/ERR2298236.bedgraph.csv")
ERR2298237 <- read.csv("C:/Users/danie/OneDrive/Documents/Wray_Lab/gynandromorph_2024/ERR2298237.bedgraph.csv")
ERR2298254 <- read.csv("C:/Users/danie/OneDrive/Documents/Wray_Lab/gynandromorph_2024/ERR2298254.bedgraph.csv")
ERR2298255 <- read.csv("C:/Users/danie/OneDrive/Documents/Wray_Lab/gynandromorph_2024/ERR2298255.bedgraph.csv")
ERR2298256 <- read.csv("C:/Users/danie/OneDrive/Documents/Wray_Lab/gynandromorph_2024/ERR2298256.bedgraph.csv")
ERR2298257 <- read.csv("C:/Users/danie/OneDrive/Documents/Wray_Lab/gynandromorph_2024/ERR2298257.bedgraph.csv")
ERR2298260 <- read.csv("C:/Users/danie/OneDrive/Documents/Wray_Lab/gynandromorph_2024/ERR2298260.bedgraph.csv")
ERR2298261 <- read.csv("C:/Users/danie/OneDrive/Documents/Wray_Lab/gynandromorph_2024/ERR2298261.bedgraph.csv")
ERR2298262 <- read.csv("C:/Users/danie/OneDrive/Documents/Wray_Lab/gynandromorph_2024/ERR2298262.bedgraph.csv")
ERR2298263 <- read.csv("C:/Users/danie/OneDrive/Documents/Wray_Lab/gynandromorph_2024/ERR2298263.bedgraph.csv")
ERR2298264 <- read.csv("C:/Users/danie/OneDrive/Documents/Wray_Lab/gynandromorph_2024/ERR2298264.bedgraph.csv")
ERR2298265 <- read.csv("C:/Users/danie/OneDrive/Documents/Wray_Lab/gynandromorph_2024/ERR2298265.bedgraph.csv")
ERR2298266 <- read.csv("C:/Users/danie/OneDrive/Documents/Wray_Lab/gynandromorph_2024/ERR2298266.bedgraph.csv")
ERR3789751 <- read.csv("C:/Users/danie/OneDrive/Documents/Wray_Lab/gynandromorph_2024/ERR3789751.bedgraph.csv")
ERR3789759 <- read.csv("C:/Users/danie/OneDrive/Documents/Wray_Lab/gynandromorph_2024/ERR3789759.bedgraph.csv")
ERR3790118 <- read.csv("C:/Users/danie/OneDrive/Documents/Wray_Lab/gynandromorph_2024/ERR3790118.bedgraph.csv")
ERR3790119 <- read.csv("C:/Users/danie/OneDrive/Documents/Wray_Lab/gynandromorph_2024/ERR3790119.bedgraph.csv")
ERR3790120 <- read.csv("C:/Users/danie/OneDrive/Documents/Wray_Lab/gynandromorph_2024/ERR3790120.bedgraph.csv")
ERR3790121 <- read.csv("C:/Users/danie/OneDrive/Documents/Wray_Lab/gynandromorph_2024/ERR3790121.bedgraph.csv")
ERR3790122 <- read.csv("C:/Users/danie/OneDrive/Documents/Wray_Lab/gynandromorph_2024/ERR3790122.bedgraph.csv")
ERR3790123 <- read.csv("C:/Users/danie/OneDrive/Documents/Wray_Lab/gynandromorph_2024/ERR3790123.bedgraph.csv")
ERR3790124 <- read.csv("C:/Users/danie/OneDrive/Documents/Wray_Lab/gynandromorph_2024/ERR3790124.bedgraph.csv")
ERR3790125 <- read.csv("C:/Users/danie/OneDrive/Documents/Wray_Lab/gynandromorph_2024/ERR3790125.bedgraph.csv")
ERR5466845 <- read.csv("C:/Users/danie/OneDrive/Documents/Wray_Lab/gynandromorph_2024/ERR5466845.bedgraph.csv")
ERR5466846 <- read.csv("C:/Users/danie/OneDrive/Documents/Wray_Lab/gynandromorph_2024/ERR5466846.bedgraph.csv")
ERR5466847 <- read.csv("C:/Users/danie/OneDrive/Documents/Wray_Lab/gynandromorph_2024/ERR5466847.bedgraph.csv")
ERR5466848 <- read.csv("C:/Users/danie/OneDrive/Documents/Wray_Lab/gynandromorph_2024/ERR5466848.bedgraph.csv")
ERR5466849 <- read.csv("C:/Users/danie/OneDrive/Documents/Wray_Lab/gynandromorph_2024/ERR5466849.bedgraph.csv")
ERR5466850 <- read.csv("C:/Users/danie/OneDrive/Documents/Wray_Lab/gynandromorph_2024/ERR5466850.bedgraph.csv")
```

```{r}
#| label: select-position

Start <- 1400000
End <- 1410000

ERR1307111 <- ERR1307111 |> filter(grepl(Chr,V1)) |> filter(V2 > Start) |> filter(V2 < End) |> mutate(sample = "ERR1307111")
ERR1307112 <- ERR1307112 |> filter(grepl(Chr,V1)) |> filter(V2 > Start) |> filter(V2 < End) |> mutate(sample = "ERR1307112")
ERR1307113 <- ERR1307113 |> filter(grepl(Chr,V1)) |> filter(V2 > Start) |> filter(V2 < End) |> mutate(sample = "ERR1307113")
ERR2298201 <- ERR2298201 |> filter(grepl(Chr,V1)) |> filter(V2 > Start) |> filter(V2 < End) |> mutate(sample = "ERR2298201")
ERR2298204 <- ERR2298204 |> filter(grepl(Chr,V1)) |> filter(V2 > Start) |> filter(V2 < End) |> mutate(sample = "ERR2298204")
ERR2298205 <- ERR2298205 |> filter(grepl(Chr,V1)) |> filter(V2 > Start) |> filter(V2 < End) |> mutate(sample = "ERR2298205")
ERR2298206 <- ERR2298206 |> filter(grepl(Chr,V1)) |> filter(V2 > Start) |> filter(V2 < End) |> mutate(sample = "ERR2298206")
ERR2298207 <- ERR2298207 |> filter(grepl(Chr,V1)) |> filter(V2 > Start) |> filter(V2 < End) |> mutate(sample = "ERR2298207")
ERR2298208 <- ERR2298208 |> filter(grepl(Chr,V1)) |> filter(V2 > Start) |> filter(V2 < End) |> mutate(sample = "ERR2298208")
ERR2298209 <- ERR2298209 |> filter(grepl(Chr,V1)) |> filter(V2 > Start) |> filter(V2 < End) |> mutate(sample = "ERR2298209")
ERR2298210 <- ERR2298210 |> filter(grepl(Chr,V1)) |> filter(V2 > Start) |> filter(V2 < End) |> mutate(sample = "ERR2298210")
ERR2298211 <- ERR2298211 |> filter(grepl(Chr,V1)) |> filter(V2 > Start) |> filter(V2 < End) |> mutate(sample = "ERR2298211")
ERR2298214 <- ERR2298214 |> filter(grepl(Chr,V1)) |> filter(V2 > Start) |> filter(V2 < End) |> mutate(sample = "ERR2298214")
ERR2298216 <- ERR2298216 |> filter(grepl(Chr,V1)) |> filter(V2 > Start) |> filter(V2 < End) |> mutate(sample = "ERR2298216")
ERR2298219 <- ERR2298219 |> filter(grepl(Chr,V1)) |> filter(V2 > Start) |> filter(V2 < End) |> mutate(sample = "ERR2298219")
ERR2298221 <- ERR2298221 |> filter(grepl(Chr,V1)) |> filter(V2 > Start) |> filter(V2 < End) |> mutate(sample = "ERR2298221")
ERR2298224 <- ERR2298224 |> filter(grepl(Chr,V1)) |> filter(V2 > Start) |> filter(V2 < End) |> mutate(sample = "ERR1307112")
ERR2298230 <- ERR2298230 |> filter(grepl(Chr,V1)) |> filter(V2 > Start) |> filter(V2 < End) |> mutate(sample = "ERR1307112")
ERR2298231 <- ERR2298231 |> filter(grepl(Chr,V1)) |> filter(V2 > Start) |> filter(V2 < End) |> mutate(sample = "ERR1307112")
ERR2298233 <- ERR2298233 |> filter(grepl(Chr,V1)) |> filter(V2 > Start) |> filter(V2 < End) |> mutate(sample = "ERR1307112")
ERR2298234 <- ERR2298234 |> filter(grepl(Chr,V1)) |> filter(V2 > Start) |> filter(V2 < End) |> mutate(sample = "ERR1307112")
ERR2298235 <- ERR2298235 |> filter(grepl(Chr,V1)) |> filter(V2 > Start) |> filter(V2 < End) |> mutate(sample = "ERR1307112")
ERR2298236 <- ERR2298236 |> filter(grepl(Chr,V1)) |> filter(V2 > Start) |> filter(V2 < End) |> mutate(sample = "ERR1307112")
ERR2298237 <- ERR2298237 |> filter(grepl(Chr,V1)) |> filter(V2 > Start) |> filter(V2 < End) |> mutate(sample = "ERR1307112")
ERR2298254 <- ERR2298254 |> filter(grepl(Chr,V1)) |> filter(V2 > Start) |> filter(V2 < End) |> mutate(sample = "ERR1307112")
ERR2298255 <- ERR2298255 |> filter(grepl(Chr,V1)) |> filter(V2 > Start) |> filter(V2 < End) |> mutate(sample = "ERR1307112")
ERR2298256 <- ERR2298256 |> filter(grepl(Chr,V1)) |> filter(V2 > Start) |> filter(V2 < End) |> mutate(sample = "ERR1307112")
ERR2298257 <- ERR2298257 |> filter(grepl(Chr,V1)) |> filter(V2 > Start) |> filter(V2 < End) |> mutate(sample = "ERR1307112")
ERR2298260 <- ERR2298260 |> filter(grepl(Chr,V1)) |> filter(V2 > Start) |> filter(V2 < End) |> mutate(sample = "ERR1307112")
ERR2298261 <- ERR2298261 |> filter(grepl(Chr,V1)) |> filter(V2 > Start) |> filter(V2 < End) |> mutate(sample = "ERR1307112")
ERR2298262 <- ERR2298262 |> filter(grepl(Chr,V1)) |> filter(V2 > Start) |> filter(V2 < End) |> mutate(sample = "ERR1307112")
ERR2298263 <- ERR2298263 |> filter(grepl(Chr,V1)) |> filter(V2 > Start) |> filter(V2 < End) |> mutate(sample = "ERR1307112")
ERR2298264 <- ERR2298264 |> filter(grepl(Chr,V1)) |> filter(V2 > Start) |> filter(V2 < End) |> mutate(sample = "ERR1307112")
ERR2298265 <- ERR2298265 |> filter(grepl(Chr,V1)) |> filter(V2 > Start) |> filter(V2 < End) |> mutate(sample = "ERR1307112")
ERR2298266 <- ERR2298266 |> filter(grepl(Chr,V1)) |> filter(V2 > Start) |> filter(V2 < End) |> mutate(sample = "ERR1307112")
ERR3789751 <- ERR3789751 |> filter(grepl(Chr,V1)) |> filter(V2 > Start) |> filter(V2 < End) |> mutate(sample = "ERR1307112")
ERR3789759 <- ERR3789759 |> filter(grepl(Chr,V1)) |> filter(V2 > Start) |> filter(V2 < End) |> mutate(sample = "ERR1307112")
ERR3790118 <- ERR3790118 |> filter(grepl(Chr,V1)) |> filter(V2 > Start) |> filter(V2 < End) |> mutate(sample = "ERR1307112")
ERR3790119 <- ERR3790119 |> filter(grepl(Chr,V1)) |> filter(V2 > Start) |> filter(V2 < End) |> mutate(sample = "ERR1307112")
ERR3790120 <- ERR3790120 |> filter(grepl(Chr,V1)) |> filter(V2 > Start) |> filter(V2 < End) |> mutate(sample = "ERR1307112")
ERR3790121 <- ERR3790121 |> filter(grepl(Chr,V1)) |> filter(V2 > Start) |> filter(V2 < End) |> mutate(sample = "ERR1307112")
ERR3790122 <- ERR3790122 |> filter(grepl(Chr,V1)) |> filter(V2 > Start) |> filter(V2 < End) |> mutate(sample = "ERR1307112")
ERR3790123 <- ERR3790123 |> filter(grepl(Chr,V1)) |> filter(V2 > Start) |> filter(V2 < End) |> mutate(sample = "ERR1307112")
ERR3790124 <- ERR3790124 |> filter(grepl(Chr,V1)) |> filter(V2 > Start) |> filter(V2 < End) |> mutate(sample = "ERR1307112")
ERR3790125 <- ERR3790125 |> filter(grepl(Chr,V1)) |> filter(V2 > Start) |> filter(V2 < End) |> mutate(sample = "ERR1307112")
ERR5466845 <- ERR5466845 |> filter(grepl(Chr,V1)) |> filter(V2 > Start) |> filter(V2 < End) |> mutate(sample = "ERR1307112")
ERR5466846 <- ERR5466846 |> filter(grepl(Chr,V1)) |> filter(V2 > Start) |> filter(V2 < End) |> mutate(sample = "ERR1307112")
ERR5466847 <- ERR5466847 |> filter(grepl(Chr,V1)) |> filter(V2 > Start) |> filter(V2 < End) |> mutate(sample = "ERR1307112")
ERR5466848 <- ERR5466848 |> filter(grepl(Chr,V1)) |> filter(V2 > Start) |> filter(V2 < End) |> mutate(sample = "ERR1307112")
ERR5466849 <- ERR5466849 |> filter(grepl(Chr,V1)) |> filter(V2 > Start) |> filter(V2 < End) |> mutate(sample = "ERR1307112")
ERR5466850 <- ERR5466850 |> filter(grepl(Chr,V1)) |> filter(V2 > Start) |> filter(V2 < End) |> mutate(sample = "ERR1307112")
```

```{r}
result <- bind_rows(ERR5466850, ERR5466849)

result |>
  group_by(sample) |>
  summarize(mean = mean(V4))

write_csv(result, "C:/Users/danie/OneDrive/Documents/Wray_Lab/gynandromorph_2024/joined.csv")
```

```{r}
ERR5466850 <- ERR5466850 |>
  mutate(sample = "ERR5466850")
```

```{r}
ERR5466849 <- ERR5466849 |>
  mutate(sample = "ERR5466849")
```

```{r}
left_join <- ERR5466850 |>
  left_join(ERR5466849, by = join_by(V1 == V1))
```


```{r}
inner_join <- ERR5466850 |>
  inner_join(ERR5466849, by = join_by(V1 == V1))

view(inner_join)
```


```{r}
nrow(result)
nrow(ERR5466849)
nrow(ERR5466850)

```


```{r, fig.height = 2.5, fig.width = 12}
#| label: melanic-hindwing-morphs 

plot=ggplot(ERR2298224, aes(x = V2, y = log(V4))) +
  geom_line() +
  geom_line(data=ERR1307112)+
  geom_line(data=ERR1307113)+
  geom_line(data=ERR2298231)+
  geom_line(data=ERR1307111)+
  geom_line(data=ERR2298201)+
  geom_line(data=ERR2298204)+
  geom_line(data=ERR2298207)+
  geom_line(data=ERR2298214)+
  geom_line(data=ERR2298216)+
  geom_line(data=ERR2298235)+
  geom_line(data=ERR2298233)+
  geom_line(data=ERR2298234)+
  geom_line(data=ERR2298237)+
  geom_line(data=ERR2298236)+
  theme_minimal()

plot
```

```{r, fig.height = 2.5, fig.width = 12}
#| label: yellow-bar-hindwing-morphs 

plot=ggplot(ERR2298224, aes(x = V2, y = log(V4))) +
  geom_line() +
  geom_line(data=ERR3790118)+
  geom_line(data=ERR3790119)+
  geom_line(data=ERR3790120)+
  geom_line(data=ERR3790121)+
  geom_line(data=ERR3790122)+
  geom_line(data=ERR3790123)+
  geom_line(data=ERR3790124)+
  geom_line(data=ERR3790125)+
  geom_line(data=ERR3789751)+
  geom_line(data=ERR3789759)+
  geom_line(data=ERR2298254)+
  geom_line(data=ERR2298255)+
  geom_line(data=ERR2298256)+
  geom_line(data=ERR2298257)+
  geom_line(data=ERR2298261)+
  geom_line(data=ERR2298205)+
  geom_line(data=ERR2298206)+
  geom_line(data=ERR2298207)+
  geom_line(data=ERR2298208)+
  geom_line(data=ERR2298209)+
  geom_line(data=ERR2298210)+
  geom_line(data=ERR2298211)+
  geom_line(data=ERR2298219)+
  geom_line(data=ERR2298221)+
  geom_line(data=ERR2298262)+
  geom_line(data=ERR2298263)+
  geom_line(data=ERR2298264)+
  geom_line(data=ERR2298265)+
  geom_line(data=ERR2298266)+
  theme_minimal()

plot
```
```{r}

```

```{r, fig.height = 3, fig.width = 12}

ERR1307112 |>
  ggplot(aes(x = V2, y = V4)) + 
  geom_line() +
  labs(
    x = "Scaffold Position (bp)", 
    y = "Unknown") + 
  theme_minimal() 
  
```
