---
title: 'Visualizing Low Complexity Repetitive Elements '
author: "Daniel and Krista"
date: "2024-09-03"
bibliogrpahy: citations.txt
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

```

```{r}
library(tidyverse)
```

```{r} 
#importing h. melpomene reference scaffold repetitive element info 
Repeat_Data <- read.table("C:/Users/danie/OneDrive/Documents/Wray_Lab/hmr.p_ctg.fa.out.gff", header=FALSE)

```

```{r}
#calculating length of each repetitive element entry 
Repeat_Data <- Repeat_Data %>% mutate(Repeat_Length = V5 - V4)
```


```{r}
#histogram of frequency of repeat based on length, for whole genome 
ggplot(Repeat_Data, aes(x = Repeat_Data$Repeat_Length)) + 
  scale_y_log10() +
	geom_histogram() 
```

```{r}
#counting # of repetitive elements in each scaffodl 
Repeat_Data_Summary <- Repeat_Data %>% 
group_by(V1) %>% 
summarize(count = n()) 


```

```{r}
#pie chart of # repetitive elements in each scaffold 
ggplot(Repeat_Data_Summary, aes(x=" ", y=Repeat_Data_Summary$count, fill=Repeat_Data_Summary$V1)) +
  geom_bar(stat="identity", width=1) +
  coord_polar("y", start=0) +
theme(legend.position="none")
```

```{r}
#density chart of frequency of repetitive element as a function of length 

ggplot(Repeat_Data, aes(x = Repeat_Data$Repeat_Length, color = V1)) +
  scale_y_log10() +
  geom_density(adjust = 500, linewidth = 0.75) +
theme(legend.position="none")


```


```{r} 
#made a new data frame of cumulated repetitive element length in each scaffold 
Cumulative_Repeat_Length_per_scaffold <- Repeat_Data %>% 
group_by(V1) %>% 
summarize(sum = sum(Repeat_Length)) 
glimpse(Cumulative_Repeat_Length_per_scaffold)

```

```{r}
```


```{r} 
#pie chart cumulated repetitive element length in each scaffold 

ggplot(Cumulative_Repeat_Length_per_scaffold, aes(x=" ", y=Cumulative_Repeat_Length_per_scaffold$sum, fill=Cumulative_Repeat_Length_per_scaffold$V1)) +
  geom_bar(stat="identity", width=1) +
  coord_polar("y", start=0) +
theme(legend.position="none")
```


```{r}
#bar chart cumulative repeat length as a function of scaffold 
ggplot(Cumulative_Repeat_Length_per_scaffold, aes(x= V1, y=Cumulative_Repeat_Length_per_scaffold$sum, fill=Cumulative_Repeat_Length_per_scaffold$V1)) +
  geom_bar(stat="identity") +
theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) +
theme(legend.position="none")

```
```{r}
#importing data frame of length of each scaffold in hmel reference genome 
Scaffold_Length <- read.table("C:/Users/danie/OneDrive/Documents/Wray_Lab/hmr_scaff_length.txt", header=FALSE)
```

```{r}
#data frame of density of repetitive elements in each scaffold (/__kb)
#cumulative rep. element length/scaffold length --> ratio!


combined_data <- inner_join(Cumulative_Repeat_Length_per_scaffold, Scaffold_Length, by = "V1") 
density_of_repeats_in_scaffold <- combined_data %>% mutate(repeat_density_percent = (sum/V2)*100)
density_of_repeats_in_scaffold 
```


```{r}
#bar plot of density of repetitive elements in each scaffold (as a percent)
ggplot(density_of_repeats_in_scaffold, aes(x= V1, y=repeat_density_percent, fill=V1)) +
  geom_bar(stat="identity") +
theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) +
theme(legend.position="none")

```
```{r} 
#made a new dataframe w scaffolds only w repeat percent below 90, then plotting it 
filtered_density_of_repeats_in_scaffold_for_scaffolds_below_90 <- density_of_repeats_in_scaffold |>
  filter(repeat_density_percent < 90)
  
ggplot(filtered_density_of_repeats_in_scaffold_for_scaffolds_below_90, aes(x= V1, y=repeat_density_percent, fill=V1)) +
  geom_bar(stat="identity") +
theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) +
theme(legend.position="none")

filtered_density_of_repeats_in_scaffold_for_scaffolds_below_90
```



