---
title: "Mapping Repetitive Elements in Drasophila Chromosome 4"
author: "Daniel and Krista"
date: "2024-06-06"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

packages
```{r}
library(tidyverse)

```

Importing Chromosome 2!
```{r} 
fly_repeats_chr2 <- read.table("C:/Users/danie/Downloads/fly_repeats_chr2L", header=TRUE, skip=2)

summary_chr2 <- as.data.frame(table(fly_repeats_chr2$Satellite))
class(summary)

ggplot(summary_chr2, aes(x="", y=summary_chr2$Freq, fill=summary_chr2$Var1)) +
  geom_bar(stat="identity", width=1) +
  coord_polar("y", start=0)
```

Importing Chromosome 4!
```{r} 
fly_repeats_chr4 <- read.table("C:/Users/danie/Downloads/fly_repeats", header=TRUE, skip=2)

summary_chr4 <- as.data.frame(table(fly_repeats_chr4$LTR.Pao))
class(summary)

ggplot(summary_chr4, aes(x=" ", y=summary_chr4$Freq, fill=summary_chr4$Var1)) +
  geom_bar(stat="identity", width=1) +
  coord_polar("y", start=0)
```

```{r}
Chromosome_2 <- summary_chr2 %>%
  mutate(Chromosome = "2")

Chromosome_4 <- summary_chr4 %>%
  mutate(Chromosome = "4")

Fly_Genome_Repeats <- rbind(Chromosome_2, Chromosome_4)
 
# Stacked + percent
ggplot(Fly_Genome_Repeats, aes(fill=Var1, y=Freq, x=Chromosome)) + 
    geom_bar(position="fill", stat="identity")

# Stacked
ggplot(Fly_Genome_Repeats, aes(fill=Var1, y=Freq, x=Chromosome)) + 
    geom_bar(position="stack", stat="identity")
```
```{r}
Chromosome_2_Scaled <- summary_chr2 %>%
  mutate(Chromosome = "2") %>%  mutate(Freq = as.integer(Freq / 1800))


Chromosome_4_Scaled <- summary_chr4 %>%
  mutate(Chromosome = "4") %>%  mutate(Freq = as.integer(Freq / 52))

Fly_Genome_Repeats_Scaled <- rbind(Chromosome_2_Scaled, Chromosome_4_Scaled)
 
# Stacked/bp
ggplot(Fly_Genome_Repeats_Scaled, aes(fill=Var1, y=Freq, x=Chromosome)) + 
    geom_bar(position="stack", stat="identity") + 
    ylab("Repeat Count per 100 kb") +
    xlab("Chromosome Number") +
    ggtitle("Repeat Count per 100 kb")



```

