
rule targets:
    input:
        "../analysis/snake/bc2011.bp.p_ctg.gfa", #assembly
        "../logs/bc2011.log",
        "../results/bc2011.linear_plot.png", #fasta_qc
        "../results/allAnnotation_bc2011.gff" #annotations
        

rule assembly:
    input:
        rawDataPath = "../raw_data/reads/m84165_231212_214911_s4.hifi_reads.bc2011.bam.fa"                                   
    output:
        "../analysis/snake/{sample}.bp.p_ctg.gfa",
        "../logs/{sample}.log"
    resources:
        runtime = "6h",
        mem_mb = 50000
    shell:
        """
        bash hifiAssembly.sh {wildcards.sample} {input.rawDataPath}
        """
    

rule fasta_qc:
    input:
        rawDataPath = "../raw_data/reads/m84165_231212_214911_s4.hifi_reads.bc2011.bam.fa"                                    
    output:
        "../results/{sample}.linear_plot.png"   #can you make genomescope output to add name** bash command #"fastaAnalyses/contig_{sample}.txt"
    shell:
        """
        bash kmerAnalysis.sh {wildcards.sample} {input.rawDataPath}
        """


rule masking:
    input: 
        "../analysis/snake/{sample}.bp.p_ctg.gfa"
    output:
        "../results/{sample}.bp.p_ctg.masked.fasta"
    shell:
        """
        bash scripts/maskingFasta.py"
        """

rule geneAnnotations:
    input:
        "../results/{sample}.bp.p_ctg.masked.fasta"
    output:
        "../analysis/geneAnnotation_{sample}.gff"
    script:
        "scripts/geneGFF.py" 

rule noncodingAnnotations:
    input:
        "../results/{sample}.bp.p_ctg.masked.fasta"
    output:
        "../analysis/noncodingAnnotation_{sample}.gff"
    script:
        "scripts/noncodingGFF.py" 

rule combinedGFF:
    input:
        "../analysis/geneAnnotation_{sample}.gff",
        "../analysis/noncodingAnnotation_{sample}.gff"
    output:
        "../results/allAnnotation_{sample}.gff"
    script:
        "combineGFF.py"